name: CI

on:
  push:
    branches: [ main, feat/upgrade-package ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2', '8.3' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-source --dev

      - name: Run PHP Code Sniffer (PSR12)
        run: ./vendor/bin/phpcs --standard=psr12 src/

      - name: Run PHPUnit tests with coverage
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v5.3.1